config/routes.rb
Rails.application.routes.draw do

devise_for :users

resources :projects do 
  resources :tasks
end

resources :projects do 
  resources :discussions
  resources :members, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy,]
end

resources :discussions do 
  resources :comments
end

resources :favorites, only: [:index]

root "projects#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :discussion
  belongs_to :user
  belongs_to :user

  validates :body, presence: {message: "must be provided"}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def create 

    @discussion = Discussion.find(params[:discussion_id])
    @comment = @discussion.comments.new(params.require(:comment).permit(:body))
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        if @comment.user != @discussion.user
          #CommentMailer.notify_discussion_owner(@comment).deliver
          format.html { redirect_to @discussion.project, notice: "Comment created successfully" }
          format.js   { render }
        else
          format.html { redirect_to @discussion.project, alert: "Couldn't create comment" }
          format.js   { render }
        end
      end
    end
  end

  def edit 

    @discussion = Discussion.find(params[:discussion_id])
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.js { render }
    end
  end  

  def update

    @discussion = Discussion.find(params[:discussion_id])
    @comment = @discussion.comments.find(params[:id]) 
    respond_to do |format|
      if @comment.update_attributes(params.require(:comment).permit(:body))
        format.html { redirect_to @discussion.project, notice: "Comment updated successfully" }
        format.js { render }
      else
        format.js { render }
        flash.now[:alert] = "Oops, something went wrong"
      end   
    end
  end


  def destroy
    @discussion = Discussion.find(params[:discussion_id])
    @comment = @discussion.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @discussion.project, notice: "Comment deleted successfully" }
      format.js { render }
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.div{id: dom_id(comment)}
  = comment.body
  %br/
  = link_to "Edit", edit_discussion_comment_path(discussion, comment), class: "btn btn-primary btn-sm", remote: true, data: {toggle: "modal", target: "#edit-comment"}
  = button_to "Delete", [discussion, comment], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm", remote: true
  %hr

app/views/comments/_comment_form.html.haml
.form
  = form_for [@discussion, @comment], remote: true do |f|
    .form-group
    = f.text_area :body, class: "form-control"
    %br
    = f.submit class: "btn btn-info"

app/views/comments/_edited_comment.html.haml
= comment.body
%br/
= link_to "Edit", edit_discussion_comment_path(discussion, comment), class: "btn btn-primary btn-sm", remote: true, data: {toggle: "modal", target: "#edit-comment"}
= button_to "Delete", [discussion, comment], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm", remote: true
%hr

app/views/comments/create.js.haml
$("##{dom_id(@discussion)} .comments").prepend("#{j render partial: '/comments/comment', locals: {discussion: @discussion, comment: @comment} }");

$("##{dom_id(@discussion)} #comment_body").val("");

app/views/comments/destroy.js.haml
$("##{dom_id(@comment)}").fadeOut(1000, function() { $(this).remove() });

app/views/comments/edit.html.haml
= render "comment_form"


  

app/views/comments/edit.js.haml
$("#edit-comment .modal-body").html("#{j render partial: 'comments/comment_form', locals: {discussion: @discussion, comment: @comment} }");

app/views/comments/update.js.haml
- if @comment.errors.any?
  $("#edit-comment .edit-comment-errors").html("#{j render partial: 'shared/standard_errors', locals: {object: @comment}}")

- else 
  $("##{dom_id(@comment)}").html("#{j render partial: 'comments/edited_comment', locals: {discussion: @discussion, comment: @comment}}");

  $("#edit-comment").modal('hide');

  $("#edit-comment .edit-comment-errors").html("");