config/routes.rb
Rails.application.routes.draw do

devise_for :users

resources :projects do 
  resources :tasks
end

resources :projects do 
  resources :discussions
  resources :members, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy,]
end

resources :discussions do 
  resources :comments
end

resources :favorites, only: [:index]

root "projects#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :body, presence: {message: "must be provided"}
  

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]

def create 

  @project = Project.find(params[:project_id])
  @task = @project.tasks.new(params.require(:task).permit(:body, :action))
  @task.user = current_user
  respond_to do |format|
    if @task.save
      format.html {redirect_to @project, notice: "Task was successfully created"}
      format.js { render } #render create.js.haml
    else
      format.html { redirect_to @project, alert: "Something went wrong, please try again" }
      format.js { render }
      flash.now[:alert] = "Couldn't create task"
    end
  end
end


def destroy

  @project = Project.find(params[:project_id])
  @task = @project.tasks.find(params[:id])
  @task.destroy 
  respond_to do |format|
    format.html {redirect_to @project, notice: "Task was successfully deleted"}
    format.js { render }
  end
end

def edit

  @project = Project.find(params[:project_id])
  @task = @project.tasks.find(params[:id])
  respond_to do |format|
    format.js { render }
  end
end

def update

  @project = Project.find(params[:project_id])
  @task = @project.tasks.find(params[:id])
  respond_to do |format|
    if @task.update_attributes(params.require(:task).permit(:body, :action))
      if @task.user != @project.user
        #TaskMailer.notify_task_owner(@task).deliver
      end
      format.html {redirect_to @project, notice: "Task was successfully updated"}
      format.js { render }
    else
      format.js { render }
      flash.now[:alert] = "Please use form to update"
    end
  end
end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_edit_form.html.haml
.form
  =form_for [@project, @task], remote: true do |f|
    .form-group
      = f.text_area :body, class: "form-control", rows: 5
    .form-group
      = f.label "Done"
      = f.check_box :action, :value => 1
    
    = f.submit class: "btn btn-primary"

app/views/tasks/_edited_task.html.haml
%p= task.body
= link_to "Edit", edit_project_task_path(@project, task), remote: true, data: {toggle: "modal", target: "#edit-task"}, class: "btn btn-info"
= button_to "Delete", [project, task], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger", remote: true
- if task.action
  .pull-right Done
- else
  .pull-right Not Done

app/views/tasks/_task.html.haml
.well{id: dom_id(task)}
  #task-body= task.body
  = link_to "Edit", edit_project_task_path(@project, task), remote: true, data: {toggle: "modal", target: "#edit-task"}, class: "btn btn-info"
  = button_to "Delete", [project, task], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger", remote: true
  - if task.action
    .pull-right Done
  - else
    .pull-right Not Done
  

      

app/views/tasks/create.js.haml
- if @task.errors.any?
  $(".task-errors").html("#{j render partial: "/shared/standard_errors", locals: {object: @task} }");
  $(".flash-messages").html("#{j render '/layouts/flash_messages'}");
- else
  $(".tasks").prepend("#{j render partial: "/tasks/task", locals: {project: @project, task: @task} }");

  $("#task_body").val("");
  $(".task-errors").html("");
  $(".flash-messages").html("");
  
  

app/views/tasks/destroy.js.haml
$("##{dom_id(@task)}").fadeOut(1000, function() { $(this).remove() } );

app/views/tasks/edit.html.haml
= render "edit_form"

app/views/tasks/edit.js.haml
$("#edit-task .modal-body").html("#{j render partial: 'tasks/edit_form', locals: {project: @project, task: @task} }");

app/views/tasks/update.js.haml
- if @task.errors.any?
  $("#edit-task .edit-task-errors").html("#{j render partial: 'shared/standard_errors', locals: {object: @task}}");
- else 
  $("##{dom_id(@task)}").html("#{j render partial: 'tasks/edited_task', locals: {project: @project, task: @task}}");

  $("#edit-task").modal('hide');
  $("#edit-task .edit-task-errors").html("");