config/routes.rb
Rails.application.routes.draw do

devise_for :users

resources :projects do 
  resources :tasks
end

resources :projects do 
  resources :discussions
  resources :members, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy,]
end

resources :discussions do 
  resources :comments
end

resources :favorites, only: [:index]

root "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :discussions, dependent: :destroy
  has_many :tasks, dependent: :destroy
  belongs_to :user

  has_many :members, dependent: :destroy
  has_many :users, through: :members

  has_many :project_tags, dependent: :destroy
  has_many :tags, through: :project_tags

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  validates :title, presence: {message: "must be provided"}
  validates :description, presence: {message: "must be provided"}


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index

    @projects = Project.all
    @project = Project.new

  end

  def new

    @project = Project.new

  end

  def create

    @project = Project.new(params.require(:project).permit(:title, :description))
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: "Project created successfully" }
        format.js { render }
      else
        format.html { redirect_to projects_path, alert: "Couldn't create project" }
        format.js { render }
        flash.now[:alert] = "Couldn't create project"
      end
    end
  end

  def show

    @discussion = Discussion.new
    @comment = Comment.new
    @task = Task.new
    @ordered_list = @project.tasks.order("action DESC")
    @members = @project.members
    @member = @project.members.where(user: current_user).first
    @tags = @project.tags
    @favorite = @project.favorites.where(user: current_user).first

  end

  def edit
    respond_to do |format|
      format.js { render }
    end
  end

  def update
    @favorite = @project.favorites.where(user: current_user).first
    respond_to do |format|
      if @project.update_attributes(params.require(:project).permit(:title, :description))
        format.html { redirect_to projects_path }
        format.js { render }
      else
        format.js { render }
      end
    end
  end

  def destroy

    @project.destroy

    redirect_to projects_path, notice: "Project deleleted successfully"

  end


  private

  def find_project
    @project = Project.find(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_edited_project.html.haml
%h2= project.title
%p= project.description
%p= "By: " + "#{project.user.name_display}"
= link_to "Edit", edit_project_path(@project), class: "btn btn-primary", remote: true, data: {toggle: "modal", target: "#edit-project"}
= link_to "Delete", @project, method: :delete, data: {confirm: "Are you sure you want to delete this project?"}, class: "btn btn-danger"

- if user_signed_in?
  - if project.user != current_user
    - if @project.favorites.exists?(user: current_user)
      = link_to "<i class='glyphicon glyphicon-star'></i>".html_safe, [project, favorite], class: "btn btn-default btn-sm", method: :delete 
    - else
      = link_to "<i class='glyphicon glyphicon-star-empty'></i>".html_safe, [project, Favorite.new], class: "btn btn-default btn-sm", method: :post

/add tag form
#tag-form
- if user_signed_in?
  = form_for [project, Tag.new], remote: true do |f|
    / = f.label "Add Tag"
    = f.text_field :name, placeholder: "Add Tag"
    %br
    %br
    = f.submit class: "btn btn-success btn-sm"

app/views/projects/_form.html.haml
.form
  = form_for project, remote: true do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: "form-control"
    .form-group
      = f.label :description
      = f.text_area :description, class: "form-control"
    = f.submit class: "btn btn-success"

app/views/projects/_project.html.haml
.well{id: dom_id(project)}
  %h3= link_to project.title, project_path(project)
  %p= project.description
  %p= "By: " + "#{project.user.name_display}"

app/views/projects/create.js.haml
- if @project.errors.any?
  $(".project-errors").html("#{j render partial: '/shared/standard_errors', locals: {object: @project} }");
- else
  $(".projects").prepend("#{j render partial: '/projects/project', locals: {project: @project} }");
  $("#new-project").modal('hide');
  $("#project_title").val("");
  $("#project_description").val("");

  $(".project-errors").html("");

app/views/projects/edit.html.haml
%h1 Edit a Project
= render "form"

app/views/projects/edit.js.haml
$("#edit-project .modal-body").html("#{j render partial: 'projects/form', locals: {project: @project} }");

app/views/projects/index.html.haml
%h1 Project Management Tool

.row
  .col-md-3.col-md-offset-1
    = link_to "Create new Project", "#", class: "btn btn-success", data: {toggle: "modal", target: "#new-project"}
  .col-md-3.col-md-offset-5
    = link_to "My Favorite Projects", favorites_path, class: "btn btn-primary"


#new-project.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
        %h4#myModalLabel.modal-title Create new Project
      .modal-body
        .project-errors
        = render partial: "/projects/form", locals: {project: @project}
        



.projects
  - @projects.each do |project|
    = render partial: "/projects/project", locals: {project: project}

    

app/views/projects/new.html.haml
%h1 Create a new Project
= render "form"

app/views/projects/show.html.haml
%br
.well{id: dom_id(@project)}
  %h2= @project.title
  %p= @project.description
  %p= "By: " + "#{@project.user.name_display}"
  = link_to "Edit", edit_project_path(@project), class: "btn btn-primary", remote: true, data: {toggle: "modal", target: "#edit-project"}
  = link_to "Delete", @project, method: :delete, data: {confirm: "Are you sure you want to delete this project?"}, class: "btn btn-danger"


  //add favorite button
  - if user_signed_in?
    - if @project.user != current_user
      - if @project.favorites.exists?(user: current_user)
        = link_to "<i class='glyphicon glyphicon-star'></i>".html_safe, [@project, @favorite], class: "btn btn-default btn-sm", method: :delete 
      - else
        = link_to "<i class='glyphicon glyphicon-star-empty'></i>".html_safe, [@project, Favorite.new], class: "btn btn-default btn-sm", method: :post


  //add tag form
  .tag-errors
  #tag-form
  - if user_signed_in?
    = form_for [@project, Tag.new], remote: true do |f|
      / = f.label "Add Tag"
      = f.text_field :name, placeholder: "Add Tag"
      %br
      %br
      = f.submit class: "btn btn-success btn-sm"
  
  .tags
    - @tags.each do |tag|
      = render partial: "tags/tag", locals: {project: @project, tag: tag}

- if user_signed_in?
  - if @project.user != current_user
    - if @project.members.exists?(user_id: current_user.id)
      #remove-member= button_to "Delete me as member to this project", [@project, @member], class: "btn btn-danger", method: :delete, remote: true
    - else
      #add-member= button_to "Add me as member to this project", [@project, Member.new], class: "btn btn-primary", remote: true

.members
  - if @members.length > 0
    %h4 Members
    - @members.each do |member|
      = render partial: 'members/member', locals: {member: member}




%h3 Create a Task
.form
  = form_for [@project, @task],remote: true do |f|
    .form-group
      = f.text_area :body,  class: "form-control"
      = f.hidden_field :action, :value => 0
    %br
    = f.submit class: "btn btn-success"

.task-errors

- if @ordered_list.length > 0
  %h3 Tasks

.tasks
  - @ordered_list.each do |task|
    = render partial: "/tasks/task", locals: {project: @project, task: task}



%h3 Create a new Discussion
.form
  = form_for [@project, @discussion], remote: true do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: "form-control"
    .form-group
      = f.label :body
      = f.text_field :body, class: "form-control"
      .create-button= f.submit class: "btn btn-success"

.discussion-errors
.discussions
  - @project.discussions.each do |discussion|
    = render partial: "/discussions/discussion", locals: {project: @project, discussion: discussion, comment: @comment}



/Empty Modal for editing a task
#edit-task.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
        %h4#myModalLabel.modal-title Edit Task
      .edit-task-errors
      .modal-body
        
      .modal-footer

/Empty Modal for editing a comment
#edit-comment.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
        %h4#myModalLabel.modal-title Edit Comment
      .edit-comment-errors
      .modal-body
        
      .modal-footer

/Empty Modal for editing a project
#edit-project.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
        %h4#myModalLabel.modal-title Edit Project
      .edit-project-errors
      .modal-body
        
      .modal-footer

app/views/projects/update.js.haml
- if @project.errors.any?
  $(".edit-project-errors").html("#{j render partial: 'shared/standard_errors', locals: {object: @project} }");

- else
  $("##{dom_id(@project)}").html("#{j render partial: 'projects/edited_project', locals: {project: @project, favorite: @favorite} }");

  $("#edit-project").modal('hide');

  $(".edit-project-errors").html("");